### ISSUE TITLE
Problème de copié-collé avec espace

### ISSUE THREAD

**Issue by Thoronalag** [HEIG-GAPS/slyum#118]
Lorsque l'on souhaite faire "copié-collé" d'une chaîne de caractère dans le nom d'une classe, la modification n'est pas prise en compte si cette chaîne contient des espaces (lorsque la classe perd le focus, c'est l'ancienne valeur qui revient...).

**Comment by porchy13** [comment]
Before applying the new name, every whitespace will be replaced by an underscore.
